apiVersion: v1
kind: ConfigMap
metadata:
  name: bufeapi-laravelapp-config
data:
  APP_URL: "https://bufeapi.jcloud.jedlik.cloud"
  APP_NAME: "BufeAPI"
  APP_ENV: "local"
  APP_DEBUG: "true"
  DB_CONNECTION: "mysql"
  DB_USERNAME: "marko.milan"
  DB_HOST: "jcloud02.jedlik.eu"
  DB_DATABASE: "marko_milan_db_2"
  DB_PORT: "3306"
  LDAP_CACHE: "false"
  LDAP_LOGGING: "false"
  LDAP_CONNECTION: "default"
  LDAP_HOST: "jdc.jedlik.eu"
  LDAP_USERNAME: "cn=Vendég,ou=Idegen,dc=jedlik,dc=helyi"
  LDAP_PORT: "389"
  LDAP_BASE_DN: "dc=jedlik,dc=helyi"
  LDAP_TIMEOUT: "5"
  LDAP_SSL: "false"
  LDAP_TLS: "false"
  LDAP_SASL: "false"
  SESSION_DRIVER: "database"
  SESSION_LIFETIME: "120"
  SESSION_ENCRYPT: "false"
  SESSION_PATH: "/"
  SESSION_DOMAIN: "null"
  FRONTEND_URL: "https://bufe.jcloud.jedlik.cloud"
  BROADCAST_CONNECTION: "reverb"
  JCS_URL: "https://jedlikinfo.jedlik.eu/api/api/timetable/ringsystem/"
  MAIL_MAILER: "smtp"
  MAIL_HOST: "smtp.gmail.com"
  MAIL_PORT: "587"
  MAIL_USERNAME: "jedlikbufe@gmail.com"
  MAIL_FROM_ADDRESS: "jedlikbufe@gmail.com"
  MAIL_FROM_NAME: "JedlikBüfé"
  REVERB_HOST: "bufe-reverb-svc"
  REVERB_PORT: "8080"
  REVERB_SCHEME: "https"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bufe-api-deployment
spec:
  selector:
    matchLabels:
      app: bufe-api
  template:
    metadata:
      labels:
        app: bufe-api
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-login-secret
      containers:
        - name: bufe-api
          image: ghcr.io/zarodolgozat-13a-bkm/zarodolgozat-bufe-api
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 8000
            - name: websocket
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: bufeapi-laravelapp-config
            - secretRef:
                name: bufeapi-prod-secret
            - secretRef:
                name: bufeapi-reverb-secret
            - secretRef:
                name: bufe-api-stripe-secret
            - secretRef:
                name: bufeapi-email-secret
          volumeMounts:
            - name: bufeapi-storage
              mountPath: /var/www/html/storage/app/public
      volumes:
        - name: bufeapi-storage
          persistentVolumeClaim:
            claimName: bufeapi-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: bufe-api-cluster-ip-service
spec:
  selector:
    app: bufe-api
  type: ClusterIP
  ports:
    - protocol: TCP
      targetPort: 8000
      port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bufe-reverb-svc
spec: 
  selector:
    app: bufe-api
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 8080
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bufeapi-certificate
spec:
  secretName: bufeapi-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - bufeapi.jcloud.jedlik.cloud
    - bufeapi-ws.jcloud.jedlik.cloud

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bufe-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/enable-websocket: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - bufeapi.jcloud.jedlik.cloud
        - bufeapi-ws.jcloud.jedlik.cloud
      secretName: bufeapi-certificate
  rules:
    - host: bufeapi.jcloud.jedlik.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bufe-api-cluster-ip-service
                port:
                  number: 80
    - host: bufeapi-ws.jcloud.jedlik.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bufe-reverb-svc
                port:
                  number: 8080
---
