[supervisord]
nodaemon=true
minfds=65536
minprocs=200

[program:php-fpm]
command=php artisan serve --host=0.0.0.0 --port=9000
directory=/var/www
autostart=true
autorestart=true

[program:reverb]
command=php artisan reverb:serve --host=0.0.0.0 --port=8080
directory=/var/www
autostart=true
autorestart=true
